<div class="content">
  <div class="container_12">
    <div class="grid_8">
      <div class="pad1">
        <h2>About us</h2>
        <img class="img_inner fleft" alt="" src="<?php echo $this->basePath('images/page3_img1.jpg') ?>">
        <div class="extra_wrapper">
          <div class="text1 off1">
            <p><strong>COMPANY PROFILE</strong></p>
          </div>
          <p>Auction  Encan Canada Inc. is comprised of a team of lawyers, notaries and real estate  agents united to provide professional services adapted to the changing real estate  market in Canada. Concerned about the failing of the traditional methods of  real estate sales </p>
        </div>
        <div class="clear"></div>
        <h2 class="head2">OUR COMMITMENT</h2>
        <p><br>
          We are committed  to investing in leading edge laboratory equipment and engaging qualified  experts. This ensures we provide accurate results and quick results for your  company. </p>
        <h2 class="head2">MANAGEMENT TEAM</h2>
        <ul>
          <li>Chartered Real Estate Broker: Clifford Letovsky,  president of the well respected Letovsky real estate group is a North American  wide deal maker. He has brokered sale of multi-milion dollar commercial and  residential complexes all over the United States and Canada. Integrity and  professionalism is his hallmark. Contact him to list your property in our  auctions.&nbsp; &nbsp;&nbsp;&nbsp;</li>
          <li>Chief Legal Consultant: Me Daniel Brook B.COM  LL.B is currently managing partner of a boutique law firm specialized in  litigation and government relations. </li>
          <li>Notary and Auction Adjudicator: Me Susan  Tremblay is a graduate of the University of Ottawa, having practiced as an attorney  for many years, she is now focused primarily on property transactions and is  responsible for the legal aspect of our auctions.</li>
        </ul>
        <p>Managing Partner: Daniel W.K. Rafuse LL.L, LL.B  served as the Chairman of the Canada Pension Tribunal and managing partner of  several major realty holding companies. </p>
        <p>&nbsp;</p>
      </div>
        <div class="grid_4 alpha">
          <div class="pad2">
            <img class="img_inner" alt="" src="<?php echo $this->basePath('images/page3_img2.jpg') ?>">
            <div class="text1">Property Management Services</div>Lorem ipsum dolor sitemen amet consectetur adip sicing elit, sed do eiusmod tempor incididunt uten labore et dolore magna aliquat enim. Minim veniam quis nostrud exercitato ullamco labo ris nisi aliquip ex ea commodo consequa uis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur excepteur sint.
            <br>
            <a class="btn" href="http://livedemo00.template-help.com/wt_45034/index-2.html#">more</a>
          </div>
        </div>
        <div class="grid_4 omega">
          <div class="pad2">
            <img class="img_inner" alt="" src="<?php echo $this->basePath('images/page3_img3.jpg') ?>">
            <div class="text1">Property Leasing Services</div>Lorem ipsum dolor sitemen amet consectetur adip sicing elit, sed do eiusmod tempor incididunt uten labore et dolore magna aliquat enim. Minim veniam quis nostrud exercitato ullamco labo ris nisi aliquip ex ea commodo consequa uis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur excepteur sint.
            <br>
            <a class="btn" href="http://livedemo00.template-help.com/wt_45034/index-2.html#">more</a>
          </div>
        </div>
        <div class="clear"></div>
      
    </div>
    <div class="grid_4">
      <h2>Why use Rent4Me</h2>
      <ul class="list2">
        <li>
          <div class="count">1</div>
          <div class="extra_wrapper">
            <div class="text1">It's Competitive <br>
Out There</div></div>
            <a href="http://livedemo00.template-help.com/wt_45034/index-2.html#">Icing elit, sed do eiusmod tempor incididunt ut labore et doloreme magna aliqua. Utem enim minim veniam quis nostrud exercita tion ullamco laboris nisi utaliquip ex ea commodo consequa uis aute.</a>
          
        </li>
        <li>
          <div class="count">2</div>
          <div class="extra_wrapper">
            <div class="text1">No One Rents <br>
Faster Than Us</div></div>
            <a href="http://livedemo00.template-help.com/wt_45034/index-2.html#">Lorem ipsum dolor sitemen amet consectetur adipis icing elit, sed do eiusmod tempor incididunt ut labore et doloreme magna aliqua. Utem enim minim veniam quis nostrud exercita tion ullamco laboris.</a>
        </li>
        <li>
          <div class="count">3</div>
          <div class="extra_wrapper">
            <div class="text1">More Exclusive <br>
Inventory</div></div>
            <a href="http://livedemo00.template-help.com/wt_45034/index-2.html#">Icing elit, sed do eiusmod tempor incididunt ut labore et doloreme magna aliqua. Utem enim minim veniam quis nostrud exercita tion ullamco laboris nisi utaliquip ex ea commodo consequa uis aute.</a>
        </li>
        <li>
          <div class="count">4</div>
          <div class="extra_wrapper">
            <div class="text1">Our Landlords <br>
Trust Us</div></div>
            <a href="http://livedemo00.template-help.com/wt_45034/index-2.html#">Lorem ipsum dolor sitemen amet consectetur adipis icing elit, sed do eiusmod tempor incididunt ut labore et doloreme magna aliqua. Utem enim minim veniam quis nostrud exercita tion ullamco laboris.</a>
        </li>
        <li>
          <div class="count">5</div>
          <div class="extra_wrapper">
            <div class="text1">Every Deal is a <br>
BIG Deal</div></div>
            <a href="http://livedemo00.template-help.com/wt_45034/index-2.html#">Icing elit, sed do eiusmod tempor incididunt ut labore et doloreme magna aliqua. Utem enim minim veniam quis nostrud exercita tion ullamco laboris nisi utaliquip ex ea commodo consequa uis aute.</a>
        </li>
        <li>
          <div class="count">6</div>
          <div class="extra_wrapper">
            <div class="text1">We Work Around<br>
Your Schedule</div></div>
            <a href="http://livedemo00.template-help.com/wt_45034/index-2.html#">Lorem ipsum dolor sitemen amet consectetur adipis icing elit, sed do eiusmod tempor incididunt ut labore et doloreme magna aliqua. Utem enim minim veniam quis nostrud exercita tion ullamco laboris.</a>
        </li>
      </ul>
    </div>
  </div>
</div>