<div class="content">
  <div class="container_12">
    <div class="grid_12">
      <h2>Properties</h2>
    </div>
    <div class="clear"></div>
    <div class="boxes">
        
         <?php foreach($paginator as $seller) : ?>
        
      
        
      <div class="grid_4">
        <div class="box">
          <div style="height: 358px;" class="maxheight"><div class="box_inner">
            <img class="img_inner" alt="" src="<?php echo $this->basePath(); ?>/tmpuploads/<?php echo $seller->property_image;?>">
            <div class="text1">
              <ul>
                <ul>
                  <li><strong><?php echo $this->escapeHtml($seller->property_title);?></strong></li>
                </ul>
              </ul>
            </div>
            <p><strong>Reserve Price 2.4 million</strong></p>
            <br>
            <a class="btn" href="<?php echo $this->url('seller') ?>/details/<?php echo $this->escapeHtml($seller->id);?>">more</a>
          </div></div>
        </div>
      </div>

       
    
      
       <?php endforeach; ?>
     
     
    </div>
  </div>
</div>

<?php
    echo $this->paginationControl(
            $paginator, 'Sliding', 'paginator-slide', array('order_by' => $order_by, 'order' => $order)
    );
    ?>