<h2>Property Details Page</h2>


<style type="text/css">
    
    label{width:150px;float:left;font-weight:bold;}
    .field_container{margin-top:8px;}
    
    .form_container{width:400px;margin: 0px auto;margin-top: 20px; height: 500px;}
    button{width:80px;margin-left:200px;margin-top: 30px; }
    
</style>


<div>
    
    <?php 
    
    $property_details = $this->property_details;
    ?>
    
     <?php
    //print_r($property_details);
    
    //exit;
    
  ?>
    
    <label>Property Title:</label>
    <div><?php echo $this->escapeHtml($property_details->property_title);?></div>
    
    <label>Property Description:</label>
    
     <div><?php echo $this->escapeHtml($property_details->property_description);?></div>
    
    <label>State:</label>
     <div><?php echo $this->escapeHtml($property_details->state);?></div>
     
     <label>City:</label>
     <div><?php echo $this->escapeHtml($property_details->city);?></div>
     
     <label>Zip</label>
     <div><?php echo $this->escapeHtml($property_details->zip);?></div>
     
     <label>Country</label>
     <div><?php echo $this->escapeHtml($property_details->country);?></div>
    
    
     <img src="<?php echo $this->basePath(); ?>/tmpuploads/<?php echo $property_details->property_image?>" alt="" class="img_inner" width="400" height="400">
     
    
</div>




    <?php if(!$this->zfcUserIdentity()): ?>
    <!-- display the login form -->
    
    <h2>Please Login</h2>
    <br/>
    
    <?php echo $this->zfcUserLoginWidget(array('redirect'=>'application')); ?>
<?php else: ?>
    
    <div class="form_container">
  <?php $form->prepare(); // The correct enctype is set here 
  
  $form->setAttribute('action', $this->url('seller', array('action' => 'details')));
  
  ?>
<?php echo $this->form()->openTag($form); ?>

    <div class="field_container">
    
        <label>Email Address:</label>
        <div><?php echo $this->formRow($form->get('user_email')); ?></div>
    
    </div>
   
    

    <button>Submit</button>

<?php echo $this->form()->closeTag(); ?>

</div>

<?php endif?>


