<div class="content">
  <div class="container_12">
    <div class="grid_8">
      <div class="pad1">
        <h2>FAQ</h2>
        <div class="extra_wrapper">
          <div class="text1 off1"><a href="#">Q. What is a Real Estate Auction?</a></div>
          <p>A. &nbsp;In America and throughout the  world it is one of&nbsp; the most popular way  to sell real estate. It is coming to Canada in a big way A real estate auction  is an innovative and effective method of selling real estate. It is an intense,  accelerated real estate marketing process that involves the public sale of any  property&mdash;most certainly including those that are nondistressed&mdash;through open &nbsp;and competitive bidding. </p>
        </div>
        <div class="extra_wrapper">
          <div class="text1 off1"><a href="#">Q. How will auction benefit me?</a></div>
          <p>A.The real estate auction is a win-win proposition for everyone  involved. For sellers you will get to sell your property fast without paying  any commission thus allowing you to lower your sale price. For buyers this  process takes the mystery out of purchasing property by obtaining an  independent inspection and appraisal you will take the guesswork out of the  property buying experience. </p>
        </div>
        <div class="extra_wrapper">
          <div class="text1 off1">
            <p><strong><a href="#">Q. How does your auction work?</a></strong></p>
          </div>
          <p>A.  All registered bidders receive a disclosure package containing all available  information related to the property. If properties are sold with legal warranty  an accredited inspection report from our independent partner Amerinspec is  provided along with an independent appraisal to remove the guesswork from your  property purchase.&nbsp; Each property has a  viewing dates each Sunday preceding the auction between 1:00 pm and 4:00pm.  Once you have viewed the property you can send your sealed bid to&nbsp; the offices of Auction Encan.com situated at  3 Westmount Square, suite depositing 5% of the sum with Notary Susan Tremblay  who will hold said sum in trust and adjudicate the successful bidder on the day  of the auction . If none of the bidders met the reserve price of the Vendor  they will have one last opportunity to raise their bid in a live auction on the  auction date.</p>
        </div>
        <div class="extra_wrapper">
          <div class="text1 off1">
            <p><strong><a href="#">Q. What is a sealed bid?</a></strong></p>
          </div>
          <p>This  is a bid where the amount remains secret until the day and hour of the closing  of the auction. At the closing of the auction the adjudicator opens up the  sealed bid an the highest bidder wins the property. If and only if no bidders  reached the secret reserve price then a live auction amonst registered bidders  will take place on the day of the closing of the auction.</p>
</div>
        <div class="extra_wrapper">
          <div class="text1 off1"><a href="#"><strong>Q. How do I list my property?</strong></a></div>
          <p>This is a bid where the amount remains secret until the day and hour of  the closing of the auction. At the closing of the auction the adjudicator opens  up the sealed bid an the highest bidder wins the property. If and only if no  bidders reached the secret reserve price then a live auction amonst registered  bidders will take place on the day of the closing of the auction.</p>
        </div>
        <div class="extra_wrapper">
          <div class="text1 off1">
            <p><strong><a href="#">Q. What are the auction fees?</a></strong></p>
          </div>
          <p>Each  successful bidder will pay a buyers premium of 5% of the sale price for  residential property and 2.5% for commercial property as well as the&nbsp; costs related to the home inspection and  appraisal. The seller has no commission whatsoever to pay.</p>
</div>
        <div class="extra_wrapper">
          <div class="text1 off1">
            <p><a href="#">Q. How will auction benefit me?</a></p>
          </div>
          <p>A.The real estate auction is a win-win proposition for everyone  involved. For sellers you will get to sell your property fast without paying  any commission thus allowing you to lower your sale price. For buyers this  process takes the mystery out of purchasing property by obtaining an  independent inspection and appraisal you will take the guesswork out of the  property buying experience.</p>
        </div>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
      </div>
    </div>
    <div class="grid_4">
      <h2>Why use Rent4Me</h2>
      <ul class="list2">
        <li>
          <div class="count">1</div>
          <div class="extra_wrapper">
            <div class="text1">It's Competitive <br>
Out There</div></div>
            <a href="http://livedemo00.template-help.com/wt_45034/index-2.html#">Icing elit, sed do eiusmod tempor incididunt ut labore et doloreme magna aliqua. Utem enim minim veniam quis nostrud exercita tion ullamco laboris nisi utaliquip ex ea commodo consequa uis aute.</a>
          
        </li>
        <li>
          <div class="count">2</div>
          <div class="extra_wrapper">
            <div class="text1">No One Rents <br>
Faster Than Us</div></div>
            <a href="http://livedemo00.template-help.com/wt_45034/index-2.html#">Lorem ipsum dolor sitemen amet consectetur adipis icing elit, sed do eiusmod tempor incididunt ut labore et doloreme magna aliqua. Utem enim minim veniam quis nostrud exercita tion ullamco laboris.</a>
        </li>
        <li>
          <div class="count">3</div>
          <div class="extra_wrapper">
            <div class="text1">More Exclusive <br>
Inventory</div></div>
            <a href="http://livedemo00.template-help.com/wt_45034/index-2.html#">Icing elit, sed do eiusmod tempor incididunt ut labore et doloreme magna aliqua. Utem enim minim veniam quis nostrud exercita tion ullamco laboris nisi utaliquip ex ea commodo consequa uis aute.</a>
        </li>
        <li>
          <div class="count">4</div>
          <div class="extra_wrapper">
            <div class="text1">Our Landlords <br>
Trust Us</div></div>
            <a href="http://livedemo00.template-help.com/wt_45034/index-2.html#">Lorem ipsum dolor sitemen amet consectetur adipis icing elit, sed do eiusmod tempor incididunt ut labore et doloreme magna aliqua. Utem enim minim veniam quis nostrud exercita tion ullamco laboris.</a>
        </li>
        <li>
          <div class="count">5</div>
          <div class="extra_wrapper">
            <div class="text1">Every Deal is a <br>
BIG Deal</div></div>
            <a href="http://livedemo00.template-help.com/wt_45034/index-2.html#">Icing elit, sed do eiusmod tempor incididunt ut labore et doloreme magna aliqua. Utem enim minim veniam quis nostrud exercita tion ullamco laboris nisi utaliquip ex ea commodo consequa uis aute.</a>
        </li>
        <li>
          <div class="count">6</div>
          <div class="extra_wrapper">
            <div class="text1">We Work Around<br>
Your Schedule</div></div>
            <a href="http://livedemo00.template-help.com/wt_45034/index-2.html#">Lorem ipsum dolor sitemen amet consectetur adipis icing elit, sed do eiusmod tempor incididunt ut labore et doloreme magna aliqua. Utem enim minim veniam quis nostrud exercita tion ullamco laboris.</a>
        </li>
      </ul>
    </div>
  </div>
</div>