<?php
$title = 'Edit User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<?php if(!$this->zfcUserIdentity()): ?>
    <!-- display the login form -->
    
    <h2>Please Login</h2>
    <br/>
    
    <?php $redirect = $this->url('home').'admin/edit/'.$this->id;?>
    
    <?php echo $this->zfcUserLoginWidget(array('redirect'=>$redirect)); ?>
<?php else: ?>

<?php
$form = $this->form;
$form->setAttribute('action', 
    $this->url('admin', array('action' => 'edit', 'id'=>$this->id)));
$form->prepare();

echo $this->form()->openTag($form) . PHP_EOL;
echo $this->formHidden($form->get('user_id')) . PHP_EOL;
echo $this->formRow($form->get('username')) . PHP_EOL;
echo $this->formRow($form->get('email')) . PHP_EOL;
echo $this->formRow($form->get('checkbox')) . PHP_EOL;
echo $this->formInput($form->get('submit')) . PHP_EOL;
echo $this->form()->closeTag($form) . PHP_EOL;

endif;