<style type="text/css">
    
    label{width:150px;float:left;}
    .field_container{margin-top:8px;}
    
    .form_container{width:400px;margin: 0px auto;margin-top: 20px; height: 500px;}
    
</style>
<div class="form_container">
    
    <?php
  $form = $this->form;
$form->setAttribute('action', $this->url('registration', array('action' => 'login')));
$form->prepare();
echo $this->form()->openTag($form);
?>
<h2>Registration Form</h2>

<div class="field_container">
    <label><b>First Name</b></label>
    <?php echo $this->formRow($form->get('first_name')); ?>
    
</div>



<div class="field_container">
    <label><b>Password</b></label>
    <?php echo $this->formRow($form->get('user_pass')); ?>
    
</div>



<div class="field_container">
    <label><b>&nbsp;</b></label>
    <?php echo $this->formRow($form->get('submit')); ?>
    
</div>

<?php

echo $this->form()->closeTag();?>

</div>