
<style type="text/css">
    
   .search_area{height:50px;}
   
  
    
    
</style>

<script src="http://code.jquery.com/jquery.js"></script>

<?php  echo $this->headScript()
                ->prependFile($this->basePath() . '/src/skdslider.js');?>



<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/src/skdslider.css')?>

<script type="text/javascript">
		jQuery(document).ready(function(){
			jQuery('#demo1').skdslider({delay:5000, animationSpeed: 2000,showNextPrev:true,showPlayButton:true,autoSlide:true,animationType:'fading'});
			jQuery('#demo2').skdslider({delay:5000, animationSpeed: 1000,showNextPrev:true,showPlayButton:false,autoSlide:true,animationType:'sliding'});
			jQuery('#demo3').skdslider({delay:5000, animationSpeed: 2000,showNextPrev:true,showPlayButton:true,autoSlide:true,animationType:'fading'});
			
			jQuery('#responsive').change(function(){
			  $('#responsive_wrapper').width(jQuery(this).val());
			});
			
		});
</script>

<?php error_reporting(0); ?>

<div class="slider_area">

    
        <ul id="demo1" class="slides">
            <li>
                <img src="<?php echo $this->basePath('images/slide2.jpg') ?>" />
                <!--Slider Description example-->

            </li>
            <li><img src="<?php echo $this->basePath('images/bg_slide_1.jpg') ?>" />

            </li>
            <li><img src="<?php echo $this->basePath('images/bg_slide_3.jpg') ?>" />
                <!--NO Description Here-->
            </li>
            <li><img src="<?php echo $this->basePath('slides/4.jpg') ?>" />

            </li>
            <li><img src="<?php echo $this->basePath('slides/5.jpg') ?>" /></li>
            <li><img src="<?php echo $this->basePath('slides/6.jpg') ?>" />

            </li>
        </ul>
    

</div>
<div class="search_area"> 
    <div class="container_12">
        <div class="grid_12">                        
            <div class="search_block">
                <h2>Find Apartments For Rent</h2>
                <form id="form1" method="post">
                    <label class="input1"> 
                        <input type="text" value="City, State, ZIP or Country" onfocus="if (this.value == & quot; City, State, ZIP or Country & quot; )this.value = & quot; & quot; ;" onblur="if (this.value == & quot; & quot; )this.value = & quot; City, State, ZIP or Country & quot; ;">
                    </label>
                    <label class="input"> 
                        <span>Bedrooms:</span>
                        <input type="text" value="any" onfocus="if (this.value == & quot; any & quot; )this.value = & quot; & quot; ;" onblur="if (this.value == & quot; & quot; )this.value = & quot; any & quot; ;">
                    </label>
                    <label class="input"> 
                        <span>Bathrooms:</span>
                        <input type="text" value="any" onfocus="if (this.value == & quot; any & quot; )this.value = & quot; & quot; ;" onblur="if (this.value == & quot; & quot; )this.value = & quot; any & quot; ;">
                    </label>
                    <label class="input"> 
                        <span>Rent Max:</span>
                        <input type="text" value="any" onfocus="if (this.value == & quot; any & quot; )this.value = & quot; & quot; ;" onblur="if (this.value == & quot; & quot; )this.value = & quot; any & quot; ;">
                    </label>
                    <div class="alright"><a onclick="document.getElementById( & #39; form1 & #39; ).submit()" href="./Home_files/Home.htm" class="btn">Search</a></div>
                </form>
            </div>
        </div>  
    </div>
</div>
</header>


<!--=======content================================-->

<div class="content page1">
    <div class="container_12">
        <div class="grid_4">
            <div class="page1_box">
                <h2>Categories</h2>
                <ul class="list">
                    <li><a href="./Home_files/Home.htm">BUSINESS</a></li>
                    <li><a href="./Home_files/Home.htm">RECREATION</a></li>
                    <li><a href="./Home_files/Home.htm">City</a></li>
                    <li><a href="./Home_files/Home.htm">beach</a></li>
                    <li><a href="./Home_files/Home.htm">FAMILY</a></li>
                </ul>
                <h3>Destinations</h3>
                <ul class="list1">
                    <li><a href="./Home_files/Home.htm">new york</a></li>
                    <li><a href="./Home_files/Home.htm">Frankfurt</a></li>
                    <li><a href="./Home_files/Home.htm">Brussels</a></li>
                    <li><a href="./Home_files/Home.htm">Dubai</a></li>
                    <li><a href="./Home_files/Home.htm">Vienna</a></li>
                    <li><a href="./Home_files/Home.htm">Istanbul</a></li>
                    <li><a href="./Home_files/Home.htm">Berlin</a></li>
                </ul>
            </div>
        </div>
        <div class="grid_8">
            <h2>Featured offers</h2>
            <div class="boxes">
               

                    <?php foreach ($sellers as $seller) : ?>
                            <div class="grid_4 alpha">
                        <div class="box "><div class="maxheight" style="height: 275px;"><div class="box_inner">

                                    <?php
                                    $imageName = $seller->property_image;

                                    $baseurl = $this->basePath() . '/tmpuploads/';

                                    $imageDestination = $baseurl . $imageName;
                                    ?>
                                    <img src="<?php echo $imageDestination; ?>" alt="" class="img_inner">

                                    <div class="fr">
                                        <div class="price">$<?php echo $this->escapeHtml($seller->property_price); ?></div>
                                        <a href="<?php echo $this->url('seller') ?>/details/<?php echo $this->escapeHtml($seller->id); ?>" class="btn">More</a>
                                    </div><p class="text1"><?php echo $this->escapeHtml($seller->property_title); ?></p>
    <?php echo $this->escapeHtml($seller->property_description); ?>
                                </div></div></div>
                                    </div>
                                <?php endforeach; ?>

               
            
                
                
                
                <!--        <div class="grid_4 omega">
                          <div class="box maxheight" style="height: 275px;"><div class="box_inner"><div class="maxheight" style="height: 275px;"><div class="box_inner">
                            <img src="<?php echo $this->basePath('img/page1_img2.jpg') ?>" alt="" class="img_inner">
                            
                            <div class="fr">
                              <div class="price">$425</div>
                              <a href="./Home_files/Home.htm" class="btn">More</a>
                            </div><p class="text1">Lorem ipsum dolor</p>Сonsectetur adipisicing elit, sed do eiusmod tempor
                          </div></div></div></div>
                        </div>
                        <div class="clear"></div>-->
                <!--        <div class="grid_4 alpha">
                          <div class="box"><div class="maxheight1" style="height: 271px;"><div class="box_inner">
                            <img src="<?php echo $this->basePath('img/page1_img3.jpg') ?>" alt="" class="img_inner">
                            
                            <div class="fr">
                              <div class="price">$386</div>
                              <a href="./Home_files/Home.htm" class="btn">More</a>
                            </div><p class="text1">consectetur adipisicing</p>Adipisicing elit, sed do eiusmod tempor incididunt 
                          </div></div></div>
                        </div>-->
                <!--        <div class="grid_4 omega">
                          <div class="box"><div class="maxheight1" style="height: 271px;"><div class="box_inner">
                            <img src="<?php echo $this->basePath('img/page1_img4.jpg') ?>" alt="" class="img_inner">
                           
                            <div class="fr">
                              <div class="price">$305</div>
                              <a href="./Home_files/Home.htm" class="btn">More</a>
                            </div> <p class="text1">dolor sit amet</p>Lorem ipsum dolor sit amet, consectetur 
                          </div></div></div>
                        </div>-->
            </div>
        </div>
        <div class="grid_12">
            <h2 class="head1">How does this work?</h2>
            <div class="bottom_block">
                <ul>
                    <li><a href="./Home_files/Home.htm"><span>1</span></a>Choose a direction</li>
                    <li><a href="./Home_files/Home.htm"><span>2</span></a>SELECT APARTMENTS</li>
                    <li><a href="./Home_files/Home.htm"><span>3</span></a>BOOK ONLINE</li>
                    <li><a href="./Home_files/Home.htm"><span>4</span></a>Make Payments</li>
                    <li><a href="./Home_files/Home.htm"><span>5</span></a>Enjoy your stay!</li>
                </ul>
            </div>
        </div>  
    </div>
</div>

